### PR TITLE
v3.0 support

### PR DESCRIPTION
**Pull request by elliotmatson**
All actions that I can test on my symetrix showfile have been tested, @mrsydster additional testing would be appreciated! Specifically the push variables

### CODE REVIEW

**Comment by mrsydster** [comment]
Sounds good! Will have some time for testing this Friday.

**Comment by krocheck** [comment]
Hey, do you guys want to move forward with getting this into the betas?

**Comment by elliotmatson** [comment]
@mrsydster have you gotten to test this anymore?

**Comment by elliotmatson** [comment]
@krocheck Should we just put this into beta? It would be great if it could make the RC coming on 4/13

**Comment by mrsydster** [comment]
Sorry for the late reply. All seems to be working as intended :)

**Pull request merged**
